databaseChangeLog:
  - changeSet:
      id: 1
      author: inventory-ops
      changes:
        - createTable:
            tableName: hm_pick_task
            columns:
              - column:
                  name: id
                  type: varchar(36)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: fulfillment_node_id
                  type: varchar(36)
                  constraints:
                    nullable: false
              - column:
                  name: order_id
                  type: varchar(36)
                  constraints:
                    nullable: false
              - column:
                  name: assigned_to_user_id
                  type: varchar(36)
                  constraints:
                    nullable: true
              - column:
                  name: status
                  type: varchar(20)
                  defaultValue: "PENDING"
                  constraints:
                    nullable: false
              - column:
                  name: priority
                  type: int
                  defaultValueNumeric: 0
                  constraints:
                    nullable: false
              # BaseJpaEntity
              - column:
                  name: created_time
                  type: timestamp
              - column:
                  name: last_modified_time
                  type: timestamp
              - column:
                  name: last_modified_by
                  type: varchar(255)
              - column:
                  name: created_by
                  type: varchar(255)
              - column:
                  name: tenant
                  type: varchar(255)
              - column:
                  name: version
                  type: bigint
                  defaultValueNumeric: 0
