package com.handmade.ecommerce.catalog.search.model;

import jakarta.persistence.*;
import org.chenile.jpautils.entity.BaseJpaEntity;

/**
 * Catalog Entry Entity
 * Search index for products using PostgreSQL full-text search
 * Note: Uses Long ID for auto-increment performance in search index
 */
@Entity
@Table(name = "catalog_entry", indexes = {
    @Index(name = "idx_catalog_product", columnList = "product_id"),
    @Index(name = "idx_catalog_category", columnList = "category_id"),
    @Index(name = "idx_catalog_popularity", columnList = "popularity DESC")
})
public class CatalogEntry extends BaseJpaEntity {
    
    // Override BaseJpaEntity's String id with Long for auto-increment performance
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long numericId;
    
    @Column(name = "product_id", nullable = false, unique = true, length = 50)
    private String productId;
    
    @Column(name = "category_id", length = 50)
    private String categoryId;
    
    @Column(name = "name", length = 255)
    private String name;
    
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    /**
     * PostgreSQL tsvector for full-text search
     * Auto-generated by database trigger
     */
    @Column(name = "search_vector", columnDefinition = "tsvector", insertable = false, updatable = false)
    private String searchVector;
    
    @Column(name = "popularity", nullable = false)
    private Integer popularity = 0;
    
    @Column(name = "view_count", nullable = false)
    private Long viewCount = 0L;
    
    @Column(name = "sales_count", nullable = false)
    private Long salesCount = 0L;
    
    /**
     * Increment view count and update popularity
     */
    public void incrementViewCount() {
        this.viewCount++;
        updatePopularity();
    }
    
    /**
     * Increment sales count and update popularity
     */
    public void incrementSalesCount() {
        this.salesCount++;
        updatePopularity();
    }
    
    /**
     * Update popularity score based on views and sales
     * Formula: (sales * 10) + (views / 100)
     */
    private void updatePopularity() {
        this.popularity = (int) ((salesCount * 10) + (viewCount / 100));
    }
    
    @Override
    protected String getPrefix() {
        return "CE"; // CatalogEntry prefix
    }

    // Getters and Setters
    
    public Long getNumericId() {
        return numericId;
    }

    public void setNumericId(Long numericId) {
        this.numericId = numericId;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSearchVector() {
        return searchVector;
    }

    public void setSearchVector(String searchVector) {
        this.searchVector = searchVector;
    }

    public Integer getPopularity() {
        return popularity;
    }

    public void setPopularity(Integer popularity) {
        this.popularity = popularity;
    }

    public Long getViewCount() {
        return viewCount;
    }

    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    public Long getSalesCount() {
        return salesCount;
    }

    public void setSalesCount(Long salesCount) {
        this.salesCount = salesCount;
    }
}
