package com.handmade.ecommerce.command;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Payment order request DTO.
 * Represents a single payment to one seller.
 * 
 * Key Design Decisions (from Alex Xu):
 * 1. paymentOrderId is generated by FRONTEND (idempotency key)
 * 2. amount is String (not double) to avoid precision issues
 * 3. One payment order per seller
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentOrderRequest {

    /**
     * Payment Order ID - IDEMPOTENCY KEY
     * Generated by frontend (UUID)
     * 
     * Critical: This enables idempotency!
     * - Frontend can retry with same ID if network fails
     * - Backend detects duplicate requests
     */
    @NotBlank(message = "Payment order ID is required")
    private String paymentOrderId;

    /**
     * Seller receiving this payment
     */
    @NotBlank(message = "Seller ID is required")
    private String sellerId;

    /**
     * Amount as STRING (not double!)
     * 
     * Why String?
     * - Avoids floating-point precision errors
     * - Safe for very large or very small numbers
     * - Recommended by Stripe, PayPal, Square
     * 
     * Backend converts to BigDecimal for calculations
     */
    @NotBlank(message = "Amount is required")
    @Pattern(regexp = "^\\d+\\.\\d{2}$", message = "Amount must be in format: 123.45")
    private String amount;

    /**
     * Currency code (ISO 4217)
     * Examples: INR, USD, EUR
     */
    @NotBlank(message = "Currency is required")
    @Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be 3-letter ISO code (e.g., INR, USD)")
    private String currency;
}