# Default Configuration (falls back to h2 for easy local development)
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}

  application:
    name: homebase-ecom

  main:
    allow-bean-definition-overriding: true

server:
  port: ${SERVER_PORT:8081}

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

query:
  mapperFiles: classpath*:mapper/*.xml
  definitionFiles: classpath*:mapper/*.json

# Chenile Security Configuration (common across all environments)
chenile:
  security:
    login:
      success-url: /
      failure-url: /login?error
