spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/handmade_local
    username: premkumar
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true

  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

query:
  jpa:
    hibernate:
      show_sql: "true"
    properties:
      hibernate:
        format_sql: "true"
  datasource:
    maximumPoolSize: "10"
    type: com.zaxxer.hikari.HikariDataSource
    username: premkumar
    password:
    minimumIdle: "2"
    idleTimeout: "600000"
    jdbcUrl: jdbc:postgresql://localhost:5432/handmade_local

chenile:
  security:
    keycloak:
      host: http://localhost:8082 # Keycloak host
      port: 8080 # Keycloak port
      base:
        realm: tenant0 # Default realm
    client:
      id: handmade # OAuth2 client ID in Keycloak
      secret: Br83cgSyskRgqYHYSHJgZtBRfKWCwpem # OAuth2 client secret
    login:
      success-url: / # Redirect after successful login
      failure-url: http://localhost:8080/tenant0
    ignore: false

logging:
  level:
    liquibase: DEBUG
