apiVersion: v1
kind: Service
metadata:
  name: handmade-backend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30080
    protocol: TCP
  - name: actuator
    port: 8081
    targetPort: actuator
    nodePort: 30081
    protocol: TCP
  - name: debug
    port: 5005
    targetPort: debug
    nodePort: 30005
    protocol: TCP
  selector:
    app: handmade-backend
