package com.handmade.ecommerce.catalog.search.indexer;

import com.handmade.ecommerce.catalog.event.external.ProductApprovedEvent;
import com.handmade.ecommerce.catalog.search.model.CatalogEntry;
import com.handmade.ecommerce.catalog.search.repository.CatalogEntryRepository;
import com.handmade.ecommerce.catalog.service.integration.ExternalProductDto;
import com.handmade.ecommerce.catalog.service.integration.ProductServiceClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.event.EventListener;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Indexes products into catalog_entry for full-text search
 * Listens to ProductApprovedEvent and updates search index
 */
@Service
public class CatalogEntryIndexer {
    
    private static final Logger log = LoggerFactory.getLogger(CatalogEntryIndexer.class);
    
    @Autowired
    private CatalogEntryRepository catalogEntryRepository;
    
    @Autowired
    private ProductServiceClient productServiceClient;
    
    @EventListener
    @Async
    @Transactional
    public void onProductApproved(ProductApprovedEvent event) {
        try {
            indexProduct(event.getProductId());
        } catch (Exception e) {
            log.error("Failed to index product: {}", event.getProductId(), e);
        }
    }
    
    private void indexProduct(String productId) {
        // Fetch product data from Product Management
        ExternalProductDto product = productServiceClient
            .getProduct(productId)
            .orElseThrow(() -> new RuntimeException("Product not found: " + productId));
        
        // Find or create catalog entry
        CatalogEntry entry = catalogEntryRepository
            .findByProductId(productId)
            .orElse(new CatalogEntry());
        
        // Update fields (search_vector auto-generated by trigger)
        entry.setProductId(product.getId());
        entry.setName(product.getName());
        // Note: ExternalProductDto doesn't have description field
        // entry.setDescription(product.getDescription());
        entry.setDescription(""); // Set empty for now
        entry.setPopularity(0); // Will be updated by analytics
        entry.setViewCount(0L);
        entry.setSalesCount(0L);
        
        // Save (trigger will update search_vector)
        catalogEntryRepository.save(entry);
        
        log.info("Indexed product: {} - {}", productId, product.getName());
    }
}
