package com.handmade.ecommerce.orchestration.seller.application.workflow.commands.onboarding;

import com.handmade.ecommerce.orchestration.seller.context.SellerOnboardingContext;
import com.handmade.ecommerce.orchestration.seller.dto.StartOnboardingResponse;
import org.chenile.owiz.Command;
import org.springframework.stereotype.Component;

/**
 * Command: Return the details of a newly created onboarding case.
 */
@Component("return-new-case-command")
public class ReturnNewCaseCommand implements Command<SellerOnboardingContext> {

    @Override
    public void execute(SellerOnboardingContext context) {
        if (context.isCaseExists() || context.getCaseId() == null) {
            return;
        }

        StartOnboardingResponse response = context.getResponse();
        response.setCaseId(context.getCaseId());
        response.setStatus("NEW_CASE_CREATED");
        response.setMessage("A new seller onboarding case has been successfully initiated.");

        // Populate session details if generated by previous steps (not in start-flow
        // yet, but ready)
        response.setIdentitySessionUrl(context.getIdentitySessionUrl());
        response.setIdentitySessionId(context.getIdentitySessionId());
        response.setIdentityProvider(context.getIdentityProvider());
    }
}
