databaseChangeLog:
  - changeSet:
      id: test-data-products
      author: test
      changes:
        - insert:
            tableName: hm_product
            columns:
              - column: {name: id, value: "prod-001"}
              - column: {name: seller_id, value: "store-001"} # Required
              - column: {name: name, value: "Handmade Ceramic Mug"}
              # - column: {name: sku, value: "MUG-001"} # Removed
              - column: {name: status, value: "ACTIVE"}
              # - column: {name: product_type, value: "PHYSICAL"} # Removed
              - column: {name: brand, value: "Pottery Studio"}
              - column: {name: tenant, value: "handmade-tenant"}
              - column: {name: created_time, valueDate: "2024-01-10T09:00:00"}
        - insert:
            tableName: hm_product
            columns:
              - column: {name: id, value: "prod-002"}
              - column: {name: seller_id, value: "store-002"} # Required
              - column: {name: name, value: "Organic Lavender Soap"}
              # - column: {name: sku, value: "SOAP-LAV-001"} # Removed
              - column: {name: status, value: "ACTIVE"}
              # - column: {name: product_type, value: "PHYSICAL"} # Removed
              - column: {name: brand, value: "Organic Soaps"}
              - column: {name: tenant, value: "handmade-tenant"}
              - column: {name: created_time, valueDate: "2024-01-11T10:00:00"}
