apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: handmade-backend-pdb
spec:
  minAvailable: 2
  maxUnavailable: 1
  selector:
    matchLabels:
      app: handmade-backend
  unhealthyPodEvictionPolicy: AlwaysAllow
